use winapi::shared::{
    basetsd::{DWORD_PTR, UINT_PTR},
    minwindef::{BOOL, DWORD, FALSE, LPARAM, LPDWORD, LPVOID, LRESULT, PUINT, UINT},
    ntdef::{HANDLE, LONG, LPCSTR, LPCWSTR, LPSTR, LPWSTR},
};

use crate::{proxy, proxy_function};

// Version.dll proxy functions
proxy_function!("version.dll", GetFileVersionInfoA, (filename: LPCSTR, handle: DWORD, len: DWORD, data: LPVOID), BOOL, FALSE);
proxy_function!("version.dll", GetFileVersionInfoSizeA, (filename: LPCSTR, handle: LPDWORD), DWORD, 0);
proxy_function!("version.dll", GetFileVersionInfoW, (filename: LPCWSTR, handle: DWORD, len: DWORD, data: LPVOID), BOOL, FALSE);
proxy_function!("version.dll", GetFileVersionInfoSizeW, (filename: LPCWSTR, handle: LPDWORD), DWORD, 0);
proxy_function!("version.dll", VerQueryValueA, (block: LPVOID, sub_block: LPCSTR, buffer: *mut LPVOID, len: PUINT), BOOL, FALSE);
proxy_function!("version.dll", VerQueryValueW, (block: LPVOID, sub_block: LPCWSTR, buffer: *mut LPVOID, len: PUINT), BOOL, FALSE);
proxy_function!("version.dll", GetFileVersionInfoExA, (flags: DWORD, filename: LPCSTR, handle: DWORD, len: DWORD, data: LPVOID), BOOL, fallback: GetFileVersionInfoA(filename, handle, len, data));
proxy_function!("version.dll", GetFileVersionInfoExW, (flags: DWORD, filename: LPCWSTR, handle: DWORD, len: DWORD, data: LPVOID), BOOL, fallback: GetFileVersionInfoW(filename, handle, len, data));
proxy_function!("version.dll", GetFileVersionInfoSizeExA, (flags: DWORD, filename: LPCSTR, handle: LPDWORD), DWORD, fallback: GetFileVersionInfoSizeA(filename, handle));
proxy_function!("version.dll", GetFileVersionInfoSizeExW, (flags: DWORD, filename: LPCWSTR, handle: LPDWORD), DWORD, fallback: GetFileVersionInfoSizeW(filename, handle));
proxy_function!("version.dll", VerFindFileA, (flags: DWORD, filename: LPCSTR, win_dir: LPCSTR, app_dir: LPCSTR, cur_dir: LPSTR, cur_dir_len: PUINT, dest_dir: LPSTR, dest_dir_len: PUINT), DWORD, 0x0001);
proxy_function!("version.dll", VerFindFileW, (flags: DWORD, filename: LPCWSTR, win_dir: LPCWSTR, app_dir: LPCWSTR, cur_dir: LPWSTR, cur_dir_len: PUINT, dest_dir: LPWSTR, dest_dir_len: PUINT), DWORD, 0x0001);
proxy_function!("version.dll", VerInstallFileA, (flags: DWORD, src_filename: LPCSTR, dest_filename: LPCSTR, src_dir: LPCSTR, dest_dir: LPCSTR, cur_dir: LPCSTR, tmp_file: LPSTR, tmp_file_len: PUINT), DWORD, 0x0001);
proxy_function!("version.dll", VerInstallFileW, (flags: DWORD, src_filename: LPCWSTR, dest_filename: LPCWSTR, src_dir: LPCWSTR, dest_dir: LPCWSTR, cur_dir: LPCWSTR, tmp_file: LPWSTR, tmp_file_len: PUINT), DWORD, 0x0001);
proxy_function!("version.dll", VerLanguageNameA, (lang: DWORD, lang_name: LPSTR, lang_len: DWORD), DWORD, 0);
proxy_function!("version.dll", VerLanguageNameW, (lang: DWORD, lang_name: LPWSTR, lang_len: DWORD), DWORD, 0);
proxy_function!("version.dll", GetFileVersionInfoByHandle, (file: i32, filename: LPSTR, handle: DWORD, len: DWORD, data: LPVOID), DWORD, 0);

// Winmm.dll proxy functions
proxy_function!("winmm.dll", waveInAddBuffer, (hwi: HANDLE, pwh: LPVOID, cbwh: UINT), UINT, 0);
proxy_function!("winmm.dll", waveInClose, (hwi: HANDLE), UINT, 0);
proxy_function!("winmm.dll", waveInGetDevCapsA, (u_device_id: UINT_PTR, pwic: LPVOID, cbwic: UINT), UINT, 0);
proxy_function!("winmm.dll", waveInGetDevCapsW, (u_device_id: UINT_PTR, pwic: LPVOID, cbwic: UINT), UINT, 0);
proxy_function!("winmm.dll", waveInGetErrorTextA, (mmr_error: UINT, psz_text: LPSTR, cch_text: UINT), UINT, 0);
proxy_function!("winmm.dll", waveInGetErrorTextW, (mmr_error: UINT, psz_text: LPWSTR, cch_text: UINT), UINT, 0);
proxy_function!("winmm.dll", waveInGetID, (hwi: HANDLE, pu_device_id: PUINT), UINT, 0);
proxy_function!("winmm.dll", waveInGetNumDevs, (), UINT, 0);
proxy_function!("winmm.dll", waveInGetPosition, (hwi: HANDLE, pmmt: LPVOID, cbmmt: UINT), UINT, 0);
proxy_function!("winmm.dll", waveInMessage, (hwi: HANDLE, u_msg: UINT, dw1: DWORD_PTR, dw2: DWORD_PTR), UINT, 0);
proxy_function!("winmm.dll", waveInOpen, (phwi: *mut HANDLE, u_device_id: UINT, pwfx: LPVOID, dw_callback: DWORD_PTR, dw_instance: DWORD_PTR, fdw_open: DWORD), UINT, 0);
proxy_function!("winmm.dll", waveInPrepareHeader, (hwi: HANDLE, pwh: LPVOID, cbwh: UINT), UINT, 0);
proxy_function!("winmm.dll", waveInReset, (hwi: HANDLE), UINT, 0);
proxy_function!("winmm.dll", waveInStart, (hwi: HANDLE), UINT, 0);
proxy_function!("winmm.dll", waveInStop, (hwi: HANDLE), UINT, 0);
proxy_function!("winmm.dll", waveInUnprepareHeader, (hwi: HANDLE, pwh: LPVOID, cbwh: UINT), UINT, 0);
proxy_function!("winmm.dll", waveOutBreakLoop, (hwo: HANDLE), UINT, 0);
proxy_function!("winmm.dll", waveOutClose, (hwo: HANDLE), UINT, 0);
proxy_function!("winmm.dll", waveOutGetDevCapsA, (u_device_id: UINT_PTR, pwoc: LPVOID, cbwoc: UINT), UINT, 0);
proxy_function!("winmm.dll", waveOutGetDevCapsW, (u_device_id: UINT_PTR, pwoc: LPVOID, cbwoc: UINT), UINT, 0);
proxy_function!("winmm.dll", waveOutGetErrorTextA, (mmr_error: UINT, psz_text: LPSTR, cch_text: UINT), UINT, 0);
proxy_function!("winmm.dll", waveOutGetErrorTextW, (mmr_error: UINT, psz_text: LPWSTR, cch_text: UINT), UINT, 0);
proxy_function!("winmm.dll", waveOutGetID, (hwo: HANDLE, pu_device_id: PUINT), UINT, 0);
proxy_function!("winmm.dll", waveOutGetNumDevs, (), UINT, 0);
proxy_function!("winmm.dll", waveOutGetPitch, (hwo: HANDLE, pdw_pitch: LPDWORD), UINT, 0);
proxy_function!("winmm.dll", waveOutGetPlaybackRate, (hwo: HANDLE, pdw_rate: LPDWORD), UINT, 0);
proxy_function!("winmm.dll", waveOutGetPosition, (hwo: HANDLE, pmmt: LPVOID, cbmmt: UINT), UINT, 0);
proxy_function!("winmm.dll", waveOutGetVolume, (hwo: HANDLE, pdw_volume: LPDWORD), UINT, 0);
proxy_function!("winmm.dll", waveOutMessage, (hwo: HANDLE, u_msg: UINT, dw1: DWORD_PTR, dw2: DWORD_PTR), UINT, 0);
proxy_function!("winmm.dll", waveOutOpen, (phwo: *mut HANDLE, u_device_id: UINT, pwfx: LPVOID, dw_callback: DWORD_PTR, dw_instance: DWORD_PTR, fdw_open: DWORD), UINT, 0);
proxy_function!("winmm.dll", waveOutPause, (hwo: HANDLE), UINT, 0);
proxy_function!("winmm.dll", waveOutPrepareHeader, (hwo: HANDLE, pwh: LPVOID, cbwh: UINT), UINT, 0);
proxy_function!("winmm.dll", waveOutReset, (hwo: HANDLE), UINT, 0);
proxy_function!("winmm.dll", waveOutRestart, (hwo: HANDLE), UINT, 0);
proxy_function!("winmm.dll", waveOutSetPitch, (hwo: HANDLE, dw_pitch: DWORD), UINT, 0);
proxy_function!("winmm.dll", waveOutSetPlaybackRate, (hwo: HANDLE, dw_rate: DWORD), UINT, 0);
proxy_function!("winmm.dll", waveOutSetVolume, (hwo: HANDLE, dw_volume: DWORD), UINT, 0);
proxy_function!("winmm.dll", waveOutUnprepareHeader, (hwo: HANDLE, pwh: LPVOID, cbwh: UINT), UINT, 0);
proxy_function!("winmm.dll", waveOutWrite, (hwo: HANDLE, pwh: LPVOID, cbwh: UINT), UINT, 0);
proxy_function!("winmm.dll", midiConnect, (hmi: HANDLE, hmo: HANDLE, p_reserved: LPVOID), UINT, 0);
proxy_function!("winmm.dll", midiDisconnect, (hmi: HANDLE, hmo: HANDLE, p_reserved: LPVOID), UINT, 0);
proxy_function!("winmm.dll", midiInAddBuffer, (hmi: HANDLE, pmh: LPVOID, cbmh: UINT), UINT, 0);
proxy_function!("winmm.dll", midiInClose, (hmi: HANDLE), UINT, 0);
proxy_function!("winmm.dll", midiInGetDevCapsA, (u_device_id: UINT_PTR, pmic: LPVOID, cbmic: UINT), UINT, 0);
proxy_function!("winmm.dll", midiInGetDevCapsW, (u_device_id: UINT_PTR, pmic: LPVOID, cbmic: UINT), UINT, 0);
proxy_function!("winmm.dll", midiInGetErrorTextA, (mmr_error: UINT, psz_text: LPSTR, cch_text: UINT), UINT, 0);
proxy_function!("winmm.dll", midiInGetErrorTextW, (mmr_error: UINT, psz_text: LPWSTR, cch_text: UINT), UINT, 0);
proxy_function!("winmm.dll", midiInGetID, (hmi: HANDLE, pu_device_id: PUINT), UINT, 0);
proxy_function!("winmm.dll", midiInGetNumDevs, (), UINT, 0);
proxy_function!("winmm.dll", midiInMessage, (hmi: HANDLE, u_msg: UINT, dw1: DWORD_PTR, dw2: DWORD_PTR), UINT, 0);
proxy_function!("winmm.dll", midiInOpen, (phmi: *mut HANDLE, u_device_id: UINT, dw_callback: DWORD_PTR, dw_instance: DWORD_PTR, fdw_open: DWORD), UINT, 0);
proxy_function!("winmm.dll", midiInPrepareHeader, (hmi: HANDLE, pmh: LPVOID, cbmh: UINT), UINT, 0);
proxy_function!("winmm.dll", midiInReset, (hmi: HANDLE), UINT, 0);
proxy_function!("winmm.dll", midiInStart, (hmi: HANDLE), UINT, 0);
proxy_function!("winmm.dll", midiInStop, (hmi: HANDLE), UINT, 0);
proxy_function!("winmm.dll", midiInUnprepareHeader, (hmi: HANDLE, pmh: LPVOID, cbmh: UINT), UINT, 0);
proxy_function!("winmm.dll", midiOutCacheDrumPatches, (hmo: HANDLE, u_patch: UINT, pwkya: LPVOID, fu_cache: UINT), UINT, 0);
proxy_function!("winmm.dll", midiOutCachePatches, (hmo: HANDLE, u_bank: UINT, pwpa: LPVOID, fu_cache: UINT), UINT, 0);
proxy_function!("winmm.dll", midiOutClose, (hmo: HANDLE), UINT, 0);
proxy_function!("winmm.dll", midiOutGetDevCapsA, (u_device_id: UINT_PTR, pmoc: LPVOID, cbmoc: UINT), UINT, 0);
proxy_function!("winmm.dll", midiOutGetDevCapsW, (u_device_id: UINT_PTR, pmoc: LPVOID, cbmoc: UINT), UINT, 0);
proxy_function!("winmm.dll", midiOutGetErrorTextA, (mmr_error: UINT, psz_text: LPSTR, cch_text: UINT), UINT, 0);
proxy_function!("winmm.dll", midiOutGetErrorTextW, (mmr_error: UINT, psz_text: LPWSTR, cch_text: UINT), UINT, 0);
proxy_function!("winmm.dll", midiOutGetID, (hmo: HANDLE, pu_device_id: PUINT), UINT, 0);
proxy_function!("winmm.dll", midiOutGetNumDevs, (), UINT, 0);
proxy_function!("winmm.dll", midiOutGetVolume, (hmo: HANDLE, pdw_volume: LPDWORD), UINT, 0);
proxy_function!("winmm.dll", midiOutLongMsg, (hmo: HANDLE, pmh: LPVOID, cbmh: UINT), UINT, 0);
proxy_function!("winmm.dll", midiOutMessage, (hmo: HANDLE, u_msg: UINT, dw1: DWORD_PTR, dw2: DWORD_PTR), UINT, 0);
proxy_function!("winmm.dll", midiOutOpen, (phmo: *mut HANDLE, u_device_id: UINT, dw_callback: DWORD_PTR, dw_instance: DWORD_PTR, fdw_open: DWORD), UINT, 0);
proxy_function!("winmm.dll", midiOutPrepareHeader, (hmo: HANDLE, pmh: LPVOID, cbmh: UINT), UINT, 0);
proxy_function!("winmm.dll", midiOutReset, (hmo: HANDLE), UINT, 0);
proxy_function!("winmm.dll", midiOutSetVolume, (hmo: HANDLE, dw_volume: DWORD), UINT, 0);
proxy_function!("winmm.dll", midiOutShortMsg, (hmo: HANDLE, dw_msg: DWORD), UINT, 0);
proxy_function!("winmm.dll", midiOutUnprepareHeader, (hmo: HANDLE, pmh: LPVOID, cbmh: UINT), UINT, 0);
proxy_function!("winmm.dll", midiStreamClose, (hms: HANDLE), UINT, 0);
proxy_function!("winmm.dll", midiStreamOpen, (phms: *mut HANDLE, pu_device_id: PUINT, c_midi: DWORD, dw_callback: DWORD_PTR, dw_instance: DWORD_PTR, fdw_open: DWORD), UINT, 0);
proxy_function!("winmm.dll", midiStreamOut, (hms: HANDLE, pmh: LPVOID, cbmh: UINT), UINT, 0);
proxy_function!("winmm.dll", midiStreamPause, (hms: HANDLE), UINT, 0);
proxy_function!("winmm.dll", midiStreamPosition, (hms: HANDLE, lpmmt: LPVOID, cbmmt: UINT), UINT, 0);
proxy_function!("winmm.dll", midiStreamProperty, (hms: HANDLE, lppropdata: LPVOID, dw_property: DWORD), UINT, 0);
proxy_function!("winmm.dll", midiStreamRestart, (hms: HANDLE), UINT, 0);
proxy_function!("winmm.dll", midiStreamStop, (hms: HANDLE), UINT, 0);
proxy_function!("winmm.dll", mixerClose, (hmx: HANDLE), UINT, 0);
proxy_function!("winmm.dll", mixerGetControlDetailsA, (hmxobj: HANDLE, pmxcd: LPVOID, fdw_details: DWORD), UINT, 0);
proxy_function!("winmm.dll", mixerGetControlDetailsW, (hmxobj: HANDLE, pmxcd: LPVOID, fdw_details: DWORD), UINT, 0);
proxy_function!("winmm.dll", mixerGetDevCapsA, (u_mx_id: UINT_PTR, pmxc: LPVOID, cbmxc: UINT), UINT, 0);
proxy_function!("winmm.dll", mixerGetDevCapsW, (u_mx_id: UINT_PTR, pmxc: LPVOID, cbmxc: UINT), UINT, 0);
proxy_function!("winmm.dll", mixerGetID, (hmxobj: HANDLE, pu_mx_id: PUINT), UINT, 0);
proxy_function!("winmm.dll", mixerGetLineControlsA, (hmxobj: HANDLE, pmxlc: LPVOID, fdw_controls: DWORD), UINT, 0);
proxy_function!("winmm.dll", mixerGetLineControlsW, (hmxobj: HANDLE, pmxlc: LPVOID, fdw_controls: DWORD), UINT, 0);
proxy_function!("winmm.dll", mixerGetLineInfoA, (hmxobj: HANDLE, pmxl: LPVOID, fdw_info: DWORD), UINT, 0);
proxy_function!("winmm.dll", mixerGetLineInfoW, (hmxobj: HANDLE, pmxl: LPVOID, fdw_info: DWORD), UINT, 0);
proxy_function!("winmm.dll", mixerGetNumDevs, (), UINT, 0);
proxy_function!("winmm.dll", mixerMessage, (hmx: HANDLE, u_msg: UINT, dw1: DWORD_PTR, dw2: DWORD_PTR), UINT, 0);
proxy_function!("winmm.dll", mixerOpen, (phmx: *mut HANDLE, u_mx_id: UINT, dw_callback: DWORD_PTR, dw_instance: DWORD_PTR, fdw_open: DWORD), UINT, 0);
proxy_function!("winmm.dll", mixerSetControlDetails, (hmxobj: HANDLE, pmxcd: LPVOID, fdw_details: DWORD), UINT, 0);
proxy_function!("winmm.dll", timeBeginPeriod, (u_period: UINT), UINT, 0);
proxy_function!("winmm.dll", timeEndPeriod, (u_period: UINT), UINT, 0);
proxy_function!("winmm.dll", timeGetDevCaps, (ptc: LPVOID, cbtc: UINT), UINT, 0);
proxy_function!("winmm.dll", timeGetSystemTime, (pmmt: LPVOID, cbmmt: UINT), UINT, 0);
proxy_function!("winmm.dll", timeGetTime, (), DWORD, 0);
proxy_function!("winmm.dll", timeKillEvent, (u_timer_id: UINT), UINT, 0);
proxy_function!("winmm.dll", timeSetEvent, (u_delay: UINT, u_resolution: UINT, fptc: LPVOID, dw_user: DWORD_PTR, fu_event: UINT), UINT, 0);
proxy_function!("winmm.dll", joyConfigChanged, (dw_flags: DWORD), UINT, 0);
proxy_function!("winmm.dll", joyGetDevCapsA, (u_joy_id: UINT_PTR, pjc: LPVOID, cbjc: UINT), UINT, 0);
proxy_function!("winmm.dll", joyGetDevCapsW, (u_joy_id: UINT_PTR, pjc: LPVOID, cbjc: UINT), UINT, 0);
proxy_function!("winmm.dll", joyGetNumDevs, (), UINT, 0);
proxy_function!("winmm.dll", joyGetPos, (u_joy_id: UINT, pji: LPVOID), UINT, 0);
proxy_function!("winmm.dll", joyGetPosEx, (u_joy_id: UINT, pji: LPVOID), UINT, 0);
proxy_function!("winmm.dll", joyGetThreshold, (u_joy_id: UINT, pu_threshold: PUINT), UINT, 0);
proxy_function!("winmm.dll", joyReleaseCapture, (u_joy_id: UINT), UINT, 0);
proxy_function!("winmm.dll", joySetCapture, (hwnd: HANDLE, u_joy_id: UINT, u_period: UINT, f_changed: BOOL), UINT, 0);
proxy_function!("winmm.dll", joySetThreshold, (u_joy_id: UINT, u_threshold: UINT), UINT, 0);
proxy_function!("winmm.dll", mciDriverNotify, (hwnd_callback: HANDLE, u_device_id: UINT, u_status: UINT), BOOL, FALSE);
proxy_function!("winmm.dll", mciDriverYield, (u_device_id: UINT), UINT, 0);
proxy_function!("winmm.dll", mciExecute, (psz_command: LPCSTR), BOOL, FALSE);
proxy_function!("winmm.dll", mciFreeCommandResource, (h_resource: HANDLE), BOOL, FALSE);
proxy_function!("winmm.dll", mciGetCreatorTask, (mci_id: UINT), HANDLE, 0 as HANDLE);
proxy_function!("winmm.dll", mciGetDeviceIDA, (psz_device: LPCSTR), UINT, 0);
proxy_function!("winmm.dll", mciGetDeviceIDFromElementIDA, (dw_element_id: DWORD, psz_type: LPCSTR), UINT, 0);
proxy_function!("winmm.dll", mciGetDeviceIDFromElementIDW, (dw_element_id: DWORD, psz_type: LPCWSTR), UINT, 0);
proxy_function!("winmm.dll", mciGetDeviceIDW, (psz_device: LPCWSTR), UINT, 0);
proxy_function!("winmm.dll", mciGetDriverData, (u_device_id: UINT), DWORD_PTR, 0);
proxy_function!("winmm.dll", mciGetErrorStringA, (mcierr: DWORD, psz_text: LPSTR, cch_text: UINT), BOOL, FALSE);
proxy_function!("winmm.dll", mciGetErrorStringW, (mcierr: DWORD, psz_text: LPWSTR, cch_text: UINT), BOOL, FALSE);
proxy_function!("winmm.dll", mciGetYieldProc, (mci_id: UINT, pdw_yield_data: LPDWORD), LPVOID, 0 as LPVOID);
proxy_function!("winmm.dll", mciLoadCommandResource, (h_instance: HANDLE, lp_res_name: LPCWSTR, u_type: UINT), UINT, 0);
proxy_function!("winmm.dll", mciSendCommandA, (mci_id: UINT, u_msg: UINT, dw_param1: DWORD_PTR, dw_param2: DWORD_PTR), DWORD, 0);
proxy_function!("winmm.dll", mciSendCommandW, (mci_id: UINT, u_msg: UINT, dw_param1: DWORD_PTR, dw_param2: DWORD_PTR), DWORD, 0);
proxy_function!("winmm.dll", mciSendStringA, (lpsz_command: LPCSTR, lpsz_return_string: LPSTR, cch_return: UINT, hwnd_callback: HANDLE), DWORD, 0);
proxy_function!("winmm.dll", mciSendStringW, (lpsz_command: LPCWSTR, lpsz_return_string: LPWSTR, cch_return: UINT, hwnd_callback: HANDLE), DWORD, 0);
proxy_function!("winmm.dll", mciSetDriverData, (u_device_id: UINT, dw_data: DWORD_PTR), BOOL, FALSE);
proxy_function!("winmm.dll", mciSetYieldProc, (mci_id: UINT, fp_yield_proc: LPVOID, dw_yield_data: DWORD), BOOL, FALSE);
proxy_function!("winmm.dll", mmioAdvance, (hmmio: HANDLE, pmmioinfo: LPVOID, fu_advance: UINT), UINT, 0);
proxy_function!("winmm.dll", mmioAscend, (hmmio: HANDLE, pmmckinfo: LPVOID, fu_ascend: UINT), UINT, 0);
proxy_function!("winmm.dll", mmioClose, (hmmio: HANDLE, fu_close: UINT), UINT, 0);
proxy_function!("winmm.dll", mmioCreateChunk, (hmmio: HANDLE, pmmckinfo: LPVOID, fu_create: UINT), UINT, 0);
proxy_function!("winmm.dll", mmioDescend, (hmmio: HANDLE, pmmckinfo: LPVOID, pmmckinfo_parent: LPVOID, fu_descend: UINT), UINT, 0);
proxy_function!("winmm.dll", mmioFlush, (hmmio: HANDLE, fu_flush: UINT), UINT, 0);
proxy_function!("winmm.dll", mmioGetInfo, (hmmio: HANDLE, pmmioinfo: LPVOID, fu_info: UINT), UINT, 0);
proxy_function!("winmm.dll", mmioInstallIOProcA, (fcc_io_proc: DWORD, p_io_proc: LPVOID, dw_flags: DWORD), LPVOID, 0 as LPVOID);
proxy_function!("winmm.dll", mmioInstallIOProcW, (fcc_io_proc: DWORD, p_io_proc: LPVOID, dw_flags: DWORD), LPVOID, 0 as LPVOID);
proxy_function!("winmm.dll", mmioOpenA, (psz_file_name: LPSTR, pmmioinfo: LPVOID, fdw_open: DWORD), HANDLE, 0 as HANDLE);
proxy_function!("winmm.dll", mmioOpenW, (psz_file_name: LPWSTR, pmmioinfo: LPVOID, fdw_open: DWORD), HANDLE, 0 as HANDLE);
proxy_function!("winmm.dll", mmioRead, (hmmio: HANDLE, pch: LPSTR, cch: LONG), LONG, 0);
proxy_function!("winmm.dll", mmioRenameA, (psz_file_name: LPCSTR, psz_new_file_name: LPCSTR, pmmioinfo: LPVOID, fdw_rename: DWORD), UINT, 0);
proxy_function!("winmm.dll", mmioRenameW, (psz_file_name: LPCWSTR, psz_new_file_name: LPCWSTR, pmmioinfo: LPVOID, fdw_rename: DWORD), UINT, 0);
proxy_function!("winmm.dll", mmioSeek, (hmmio: HANDLE, l_offset: LONG, i_origin: i32), LONG, 0);
proxy_function!("winmm.dll", mmioSendMessage, (hmmio: HANDLE, u_msg: UINT, l_param1: LPARAM, l_param2: LPARAM), LRESULT, 0);
proxy_function!("winmm.dll", mmioSetBuffer, (hmmio: HANDLE, pch_buffer: LPSTR, cch_buffer: LONG, fu_buffer: UINT), UINT, 0);
proxy_function!("winmm.dll", mmioSetInfo, (hmmio: HANDLE, pmmioinfo: LPVOID, fu_info: UINT), UINT, 0);
proxy_function!("winmm.dll", mmioStringToFOURCCA, (sz: LPCSTR, u_flags: UINT), DWORD, 0);
proxy_function!("winmm.dll", mmioStringToFOURCCW, (sz: LPCWSTR, u_flags: UINT), DWORD, 0);
proxy_function!("winmm.dll", mmioWrite, (hmmio: HANDLE, pch: LPCSTR, cch: LONG), LONG, 0);
proxy_function!("winmm.dll", PlaySound, (psz_sound: LPCSTR, hmod: HANDLE, fdw_sound: DWORD), BOOL, FALSE);
proxy_function!("winmm.dll", PlaySoundA, (psz_sound: LPCSTR, hmod: HANDLE, fdw_sound: DWORD), BOOL, FALSE);
proxy_function!("winmm.dll", PlaySoundW, (psz_sound: LPCWSTR, hmod: HANDLE, fdw_sound: DWORD), BOOL, FALSE);
proxy_function!("winmm.dll", sndPlaySoundA, (psz_sound: LPCSTR, fu_sound: UINT), BOOL, FALSE);
proxy_function!("winmm.dll", sndPlaySoundW, (psz_sound: LPCWSTR, fu_sound: UINT), BOOL, FALSE);
proxy_function!("winmm.dll", auxGetDevCapsA, (u_device_id: UINT_PTR, pac: LPVOID, cbac: UINT), UINT, 0);
proxy_function!("winmm.dll", auxGetDevCapsW, (u_device_id: UINT_PTR, pac: LPVOID, cbac: UINT), UINT, 0);
proxy_function!("winmm.dll", auxGetNumDevs, (), UINT, 0);
proxy_function!("winmm.dll", auxGetVolume, (u_device_id: UINT, pdw_volume: LPDWORD), UINT, 0);
proxy_function!("winmm.dll", auxOutMessage, (u_device_id: UINT, u_msg: UINT, dw1: DWORD_PTR, dw2: DWORD_PTR), UINT, 0);
proxy_function!("winmm.dll", auxSetVolume, (u_device_id: UINT, dw_volume: DWORD), UINT, 0);
proxy_function!("winmm.dll", CloseDriver, (h_driver: HANDLE, l_param1: LPARAM, l_param2: LPARAM), LRESULT, 0);
proxy_function!("winmm.dll", DefDriverProc, (dw_driver_identifier: DWORD_PTR, h_driver: HANDLE, u_msg: UINT, l_param1: LPARAM, l_param2: LPARAM), LRESULT, 0);
proxy_function!("winmm.dll", DriverCallback, (dw_callback: DWORD, dw_flags: DWORD, h_device: HANDLE, dw_msg: DWORD, dw_user: DWORD, dw_param1: DWORD, dw_param2: DWORD), BOOL, FALSE);
proxy_function!("winmm.dll", DrvGetModuleHandle, (h_driver: HANDLE), HANDLE, 0 as HANDLE);
proxy_function!("winmm.dll", GetDriverModuleHandle, (h_driver: HANDLE), HANDLE, 0 as HANDLE);
proxy_function!("winmm.dll", OpenDriver, (sz_driver_name: LPCWSTR, sz_section_name: LPCWSTR, l_param: LPARAM), HANDLE, 0 as HANDLE);
proxy_function!("winmm.dll", SendDriverMessage, (h_driver: HANDLE, message: UINT, l_param1: LPARAM, l_param2: LPARAM), LRESULT, 0);
proxy_function!("winmm.dll", mmsystemGetVersion, (), UINT, 0);
proxy_function!("winmm.dll", mmDrvInstall, (h_driver: HANDLE, p_drv_reg_info: LPVOID), BOOL, FALSE);
proxy_function!("winmm.dll", mmGetCurrentTask, (), HANDLE, 0 as HANDLE);
proxy_function!("winmm.dll", mmTaskBlock, (h: HANDLE), UINT, 0);
proxy_function!("winmm.dll", mmTaskCreate, (lp_task_address: LPVOID, h_task_handle: *mut HANDLE, dw_inst: DWORD_PTR), UINT, 0);
proxy_function!("winmm.dll", mmTaskSignal, (h: HANDLE), UINT, 0);
proxy_function!("winmm.dll", mmTaskYield, (), UINT, 0);
proxy_function!("winmm.dll", WOWAppExit, (h_inst: HANDLE), BOOL, FALSE);
